#!/usr/bin/env python
# coding: utf8


from __future__ import unicode_literals, print_function


TAG_MAP = {
    'NOUN': {'pos': 'NOUN'},
    'VERB': {'pos': 'VERB'},
    'ADJ': {'pos': 'ADJ'},
    'PRON': {'pos': 'PRON'},
    'PUNCT': {'pos': 'PUNCT'},
	'SPACE': {'pos': 'SPACE'},
    'SYM': {'pos': 'SYM'},
	'AUX': {'pos': 'AUX'},
    'NUM': {'pos': 'NUM'},
    'ADP': {'pos': 'ADP'},
    'INTJ': {'pos': 'INTJ'},
    'PROPN': {'pos': 'PROPN'},
    'SCONJ': {'pos': 'SCONJ'},
	'CONJ': {'pos': 'CONJ'},
    'ADV': {'pos': 'ADV'}
}


TRAIN_DATA_POS = [
    ("data.", {'tags': ['NOUN', 'PUNCT']}),
    ("Que caritas x favor.", {'tags': ['SCONJ', 'NOUN', 'ADP','ADP', 'PUNCT']}),
    ("Jeje", {'tags': ['SPACE']}),
    ("Estoy en el campo con juan.", {'tags': ['AUX', 'ADP', 'DET', 'NOUN', 'ADP','PROPN','PUNCT']}),
    ("Y que haces hay te va a enpernar el gordo en medio del campo jajaja.", {'tags': ['CONJ','SCONJ','VERB','ADV','PRON','AUX','ADP','VERB','DET','ADJ','ADP','NOUN','ADP','NOUN','SPACE','PUNCT']}),
    ("Cuanto amor x dios.", {'tags': ['DET', 'NOUN', 'ADP', 'NOUN', 'PUNCT']}),
    ("Ke linda la pendeja de tu ñieta", {'tags': ['SCONJ', 'ADJ', 'DET', 'NOUN', 'ADP','DET','NOUN']}),
    ("?viste es todo amor mi guachina", {'tags': ['PUNCT', 'VERB', 'AUX', 'DET', 'NOUN','DET','NOUN']}),
    ("Mira que yegua soy yo tu sobrina", {'tags': ['VERB', 'PRON', 'NOUN', 'AUX', 'PRON','DET','NOUN']}),
    ("Estas linda dijo juan y yo tambien mejor ke en persona", {'tags': ['DET', 'ADJ', 'VERB', 'PROPN', 'CONJ','PRON','DET', 'ADJ', 'SCONJ','ADP','NOUN']}),
    ("Mira ke lindo cel tiene la cami se lo encontro la jose y se lo regalo", {'tags': ['VERB', 'SCONJ', 'ADJ', 'NOUN', 'VERB', 'DET', 'PROPN','PRON','PRON', 'VERB', 'DET','PROPN','CONJ', 'PRON','PRON','NOUN']}),
    ("Ahora qi.", {'tags': ['ADV', 'PRON', 'PUNCT']}),
    ("Es tactil.", {'tags': ['AUX', 'ADJ', 'PUNCT']}),
    ("Esta re bueno que tuje la flaca y hasta cuando te quedas ahy", {'tags': ['DET','PRON','ADJ','SCONJ','NOUN','DET','NOUN','CONJ','ADP','SCONJ','PRON','VERB','ADV']}),
    ("Asta este viernes", {'tags': ['ADP', 'DET', 'NOUN']}),
    ("A poco te duro la estadia aparte para verlo al panza no es mucho sacrificio che", {'tags': ['ADP','ADV','PRON', 'ADJ','DET','NOUN','ADV', 'ADP','VERB','ADP','NOUN','ADV','AUX','DET','NOUN','PROPN']}),
    ("Si si no puedo abandonar lo otro jeje", {'tags': ['SCONJ', 'SCONJ', 'ADV', 'AUX', 'VERB','PRON','PRON','SPACE']}),
    ("Y aparte es carne joven y tiene linda colita mmmmmm", {'tags': ['CONJ', 'ADV', 'AUX', 'NOUN','ADJ','CONJ','VERB','ADJ','NOUN','SPACE']}),
    ("Yegua es mia la cola yo la agarro con las dos manos", {'tags': ['NOUN', 'AUX', 'PROPN', 'DET', 'NOUN','PRON','PRON','VERB','ADP','DET','NUM','NOUN']}),
    ("Hla cm andas?", {'tags': ['INTJ', 'SCONJ', 'NOUN', 'PUNCT']}),
    ("Ke linda t ñeta..je.", {'tags': ['SCONJ', 'ADJ', 'DET', 'NOUN', 'PUNCT','SPACE','PUNCT']}),
    ("Kien sos?.", {'tags': ['PRON', 'INTJ', 'PUNCT', 'PUNCT', 'ADP','PROPN','PUNCT']}),
    ("Dlfina boluda", {'tags': ['PROPN', 'ADJ']}),
    ("Bueno eso de boluda esta de mas como andas", {'tags': ['ADJ', 'PRON', 'ADP', 'ADJ', 'DET','ADP','ADV','SCONJ','NOUN']}),
    ("Biem... Kagada d frio...", {'tags': ['ADV', 'PUNCT', 'ADJ', 'ADP', 'NOUN','PUNCT']}),
    ("Tambien re cagada de frio ando en la calle y tu madre como anda", {'tags': ['ADV', 'AUX', 'ADJ', 'ADP', 'NOUN','VERB','ADP', 'DET','NOUN','CONJ','DET', 'NOUN','SCONJ','VERB']}),
    ("Ke raro... Mi mama? Bien, tamos en la kasa d una amiga d eya...", {'tags': ['SCONJ', 'ADJ', 'PUNCT','DET', 'NOUN', 'PUNCT','ADV','PUNCT', 'VERB','ADP','DET','NOUN', 'ADP','DET','NOUN', 'ADP','PRON','PUNCT']}),
    ("La sofi??", {'tags': ['DET', 'PROPN', 'PUNCT', 'PUNCT']}),
    ("Bien estamos todos ahora tengo ala negra con migo no hace mucho se vino a vivir con migo", {'tags': ['ADV', 'VERB', 'PRON', 'ADV', 'VERB','DET','ADJ','PRON', 'PRON', 'ADV', 'AUX', 'ADV','PRON','VERB', 'ADP', 'VERB','PRON','PRON']}),
    ("Ah mira ke bueno...", {'tags': ['INTJ', 'VERB', 'SCONJ', 'ADJ', 'PUNCT']}),
    ("Xke c volvio?", {'tags': ['SCONJ', 'PRON', 'VERB', 'PUNCT']}),
    ("Mandale salu2 a las 2...", {'tags': ['VERB', 'NOUN', 'ADP', 'DET', 'NUM','PUNCT']}),
    ("Ke bonita la gorda.", {'tags': ['PRON', 'ADJ', 'DET', 'ADJ', 'PUNCT']}),
    ("Cm c yama?", {'tags': ['SCONJ', 'PRON', 'VERB', 'PUNCT']}),
    ("Estoy en el campo con juan.", {'tags': ['AUX', 'ADP', 'DET', 'NOUN', 'ADP','PROPN','PUNCT']}),
    ("X que le hablaron y quiso volverce y mi ñieta se llama keila y ya tiene un año", {'tags': ['ADP', 'PRON', 'PRON', 'VERB', 'CONJ','VERB','ADV','CONJ','DET','NOUN', 'PRON','VERB','PROPN','CONJ', 'ADV', 'VERB', 'DET', 'NOUN']}),
    ("Y c... Pobre negra..", {'tags': ['CONJ', 'SCONJ', 'PUNCT', 'ADJ', 'ADJ','PUNCT']}),
    ("Y la meli n volvio todavia?", {'tags': ['CONJ', 'DET', 'PROPN', 'ADV', 'VERB','NOUN','PUNCT']}),
    ("Estoy en el campo con juan.", {'tags': ['AUX', 'ADP', 'DET', 'NOUN', 'ADP','PROPN','PUNCT']}),
    ("Ke lindo nobre.", {'tags': ['SCONJ', 'ADJ', 'NOUN', 'PUNCT']}),
    ("Es re parecida a la agustina d chikita", {'tags': ['AUX', 'AUX', 'ADJ', 'ADP', 'DET','PROPN','ADP','ADJ']}),
    ("Tienen whasapp las chikas?.", {'tags': ['VERB', 'NOUN', 'DET', 'NOUN', 'PUNCT','PUNCT']}),
    ("No la meli no quiso volver y la que tiene wapsap es agustina", {'tags': ['ADV', 'DET', 'PROPN', 'ADV', 'VERB','VERB','CONJ','DET', 'PRON', 'VERB', 'NOUN', 'AUX','PROPN','PUNCT']}),
    ("M pasas el numero??.", {'tags': ['PRON', 'VERB', 'DET', 'NOUN', 'PUNCT','PUNCT','PUNCT']}),
    ("Dbe andar d novio la gringa jeje", {'tags': ['AUX', 'VERB', 'ADP', 'NOUN', 'DET','NOUN','SPACE']}),
    ("4453101 dale besos a todos", {'tags': ['NUM', 'VERB', 'NOUN', 'ADP', 'PRON']}),
    ("No si no se si es lesviana jajaaj", {'tags': ['ADV', 'SCONJ', 'ADV', 'PRON', 'SCONJ','AUX','ADJ','SPACE']}),
    ("Sta cm la valentina.", {'tags': ['PRON', 'SCONJ', 'DET', 'PROPN', 'PUNCT']}),
    ("Y no somos libres de nada viste los chicos de ahora saludos a todos", {'tags': ['CONJ','ADV','AUX','ADJ','ADP','PRON','VERB','DET','NOUN','ADP','ADV','ADJ','ADP','PRON']}),
    ("Tmb t mandan salu2 aka... Tiene cred la agustina?", {'tags': ['ADV','PRON','VERB','NOUN','NOUN','PUNCT','VERB','NOUN','DET','PROPN','PUNCT']}),
    ("No como siempre es muy raro", {'tags': ['ADV', 'SCONJ', 'ADV', 'AUX', 'ADV','ADJ']}),
    ("Ah... Entoncs n le va a yegar mi msj... Tan yendo al kole las chikas?", {'tags': ['INTJ','PUNCT','ADV','ADV','PRON','AUX','ADP','VERB','DET','NOUN','PUNCT','VERB','VERB','ADP','NOUN','DET','NOUN','PUNCT']}),
    ("C ya c...", {'tags': ['SCONJ','ADV','PRON','PUNCT']}),
    ("Pero n djaron el kole la meli y la negra n??", {'tags': ['CONJ','ADV','VERB','DET','NOUN','DET','PROPN','CONJ','DET','ADJ','ADV','PUNCT','PUNCT']}),
    ("Cm le fue a la sofi?.", {'tags': ['SCONJ','PRON','AUX','ADP','DET','PROPN','PUNCT','PUNCT']}),
    ("Holaa taradaa.", {'tags': ['DET','ADJ','PUNCT']}),
    ("Hola tolola como anda mi loca u?", {'tags': ['DET','ADJ','SCONJ','VERB','DET','NOUN','CONJ','PUNCT']}),
    ("Biien resiien se despiiertaa...", {'tags': ['ADV','ADV','PRON','VERB','PUNCT']}),
    ("Se le fue la fiebre", {'tags': ['PRON','PRON','AUX','DET','NOUN']}),
    ("Sii por ahora no tuboo", {'tags': ['SCONJ','ADP','ADV','ADV','VERB']}),
    ("A bueno cuidala y que no ande afuera", {'tags': ['ADP','ADJ','VERB','CONJ','SCONJ','ADV','VERB','ADV']}),
    ("Ke hcs??", {'tags': ['PRON','VERB','PUNCT','PUNCT']}),
    ("Dormis??", {'tags': ['VERB','PUNCT','PUNCT']}),
    ("Mira kee enfermiita ke esta tu ñiietiita!", {'tags': ['VERB','SCONJ','ADJ','SCONJ','DET','DET','NOUN','PUNCT']}),
    ("Rut!!!", {'tags': ['PROPN','PUNCT','PUNCT','PUNCT']}),
    ("Estoy haciendo la masa para los alfajores y necesito que alguien me venga a cebar mate, aca en la despensa.", {'tags': ['VERB','VERB','DET','NOUN','ADP','DET','NOUN','CONJ','VERB','SCONJ','PRON','PRON','VERB','ADP','VERB','NOUN','PUNCT','ADV','ADP','DET','NOUN','PUNCT']}),
    ("Hay pero yo	estoy llena de mates ahora estoy x cocinar", {'tags': ['INTJ','CONJ','PRON','SPACE','AUX','ADJ','ADP','NOUN','ADV','AUX','ADP','VERB']}),
    ("Estamos las dos con Candela, vamos a comer a tu casa!!", {'tags': ['VERB','DET','NUM','ADP','PROPN','PUNCT','VERB','ADP','VERB','ADP','DET','NOUN','PUNCT','PUNCT']}),
    ("Si van haceeccccer", {'tags': ['SCONJ','VERB','VERB']}),
    ("Si van hacer una sopa", {'tags': ['SCONJ','VERB','VERB','DET','NOUN']}),
    ("Mmmm que rico ! !", {'tags': ['SPACE','SCONJ','ADJ','PUNCT','PUNCT']}),
    ("Preparate mañana para hacer el tuco, que yo hago los ñoquis", {'tags': ['VERB','ADV','ADP','VERB','DET','NOUN','PUNCT','PRON','PRON','VERB','DET','NOUN']}),
    ("Bueno dale", {'tags': ['ADJ','VERB']}),
    ("Queres alitas de pollo o carne?", {'tags': ['VERB','NOUN','ADP','NOUN','CONJ','NOUN','PUNCT']}),
    ("Bueno dale mejor carne", {'tags': ['ADJ','VERB','ADJ','NOUN']}),
    ("Si queres invitala a Josefina para que venga a comer", {'tags': ['SCONJ','VERB','VERB','ADP','PROPN','ADP','SCONJ','VERB','ADP','VERB']}),
    ("Le aviso a ella", {'tags': ['PRON','VERB','ADP','PRON']}),
    ("Bueno, cherere", {'tags': ['INTJ','PUNCT','NOUN']}),
    ("Paola tu hija es insoportableeeee", {'tags': ['PROPN','PRON','NOUN','AUX','ADJ']}),
    ("Ke ases ? ,yegua", {'tags': ['PRON','VERB','PUNCT','PUNCT','NOUN']}),
    ("Hla ke hcs?", {'tags': ['INTJ','PRON','VERB','PUNCT']}),
    ("Hola Pao !!", {'tags': ['DET','PROPN','PUNCT','PUNCT']}),
    ("Porfa necesito comunicarm con vos", {'tags': ['ADP','VERB','VERB','ADP','PRON']}),
    ("Llama", {'tags': ['VERB']}),
    ("Ya estoy sola pascual veni si queres", {'tags': ['ADV','AUX','ADJ','PROPN','ADJ','SCONJ','NOUN']}),
    ("Amiga.", {'tags': ['NOUN','PUNCT']}),
    ("Mañana voy ...", {'tags': ['ADV','VERB','PUNCT']}),
    ("Bueno dale te espero", {'tags': ['ADJ','VERB','PRON','VERB']}),
    ("Pero voy a comer con la aBUELA ME BAS ACOMPAÑAR AL BANCO TENGO KE RETIRAR EL PIN", {'tags': ['CONJ','AUX','ADP','VERB','ADP','DET','NOUN','PRON','VERB','VERB','ADP','NOUN','VERB','SCONJ','VERB','DET','NOUN']}),
    ("Si dale te acompano", {'tags': ['SCONJ','VERB','PRON','VERB']}),
    ("Avisame a que hora vas al banco x que haora no estoi en casa asi yo voy para casa  y te acompaño yegua", {'tags': ['VERB','ADP','SCONJ','NOUN','VERB','ADP','NOUN','ADP','SCONJ','ADV','ADV','AUX','ADP','NOUN','ADV','PRON','VERB','ADP','NOUN','SPACE','CONJ','PRON','VERB','NOUN']}),
    ("Despues de comer tranquila", {'tags': ['ADV','ADP','VERB','ADJ']}),
    ("Gordi mañana te alcansa la plata la maga x que yo no voy a estar besos mi amor", {'tags': ['ADJ','ADV','PRON','VERB','DET','NOUN','DET','NOUN','ADP','SCONJ','PRON','ADV','AUX','ADP','VERB','NOUN','DET','NOUN']}),
    ("A dondee vass? trolaa.", {'tags': ['ADP','VERB','VERB','PUNCT','ADJ','PUNCT']}),
    ("Y como te fue con gustavo jeje", {'tags': ['CONJ','SCONJ','PRON','AUX','ADP','PROPN','SPACE']}),
    ("Mal vino y estava acompañada y se re enojo", {'tags': ['ADJ','VERB','CONJ','AUX','ADJ','CONJ','PRON','DET','NOUN']}),
    ("ACONPAÑADA CON KIEN SI TE DEJAMOS SOLA", {'tags': ['ADJ','ADP','SCONJ','SCONJ','VERB','VERB','ADJ']}),
    ("Hola amiga como andas", {'tags': ['INTJ','NOUN','SCONJ','VERB']}),
    ("Bien amigo y vos", {'tags': ['ADV','NOUN','CONJ','PRON']}),
    ("Bien amiga aca estoy en neco tomandoo un vinito con jose caceres jaaa", {'tags': ['ADV','ADJ','ADP','AUX','ADP','NOUN','VERB','DET','NOUN','ADP','PROPN','PROPN','SPACE']}),
    ("A pero estas como queres tenes camion nuevo", {'tags': ['ADP','CONJ','PRON','SCONJ','NOUN','VERB','NOUN','ADJ']}),
    ("Siiii agarre un tector x unos viajes todavia no es fijo vamos a ver q onda amiga vos q ases", {'tags': ['SCONJ','VERB','DET','NOUN','ADP','DET','NOUN','ADV','ADV','AUX','ADJ','AUX','ADP','AUX','SCONJ','NOUN','NOUN','DET','PRON','VERB']}),
    ("Aca en mi casa con unos amigos saludos a caceres entonces x lo menos estas haciendo algo", {'tags': ['ADV','ADP','DET','NOUN','ADP','DET','NOUN','ADJ','ADP','PROPN','ADV','ADP','DET','ADV','DET','VERB','PRON']}),
    ("No ay ninguna amiga para el cabezita jaaaaaa", {'tags': ['ADV','AUX','DET','NOUN','ADP','DET','NOUN','SPACE']}),
    ("Y pero se te esta dando de apoco x lo menos no estas parado", {'tags': ['CONJ','CONJ','PRON','PRON','DET','VERB','ADP','PRON','ADP','DET','ADV','ADV','DET','NOUN']}),
    ("No ay ninguna amiga para el cabezita jaaaaaa", {'tags': ['ADV','AUX','DET','NOUN','ADP','DET','NOUN','SPACE']}),
    ("Pero que queres vos cabesita", {'tags': ['CONJ','SCONJ','NOUN','PRON','ADJ']}),
    ("Jaaaaa una amiguita amiga jaaaaa", {'tags': ['SPACE','DET','NOUN','NOUN','SPACE']}),
    ("De donde son todos hombres te precento alguno si te va jajaja", {'tags': ['ADP','PRON','AUX','DET','NOUN','PRON','VERB','PRON','SCONJ','PRON','VERB','SPACE']}),
    ("Paso x ahora amiga hombres no quiereo jaaaa", {'tags': ['VERB','ADP','ADV','VERB','NOUN','ADV','VERB','SPACE']}),
    ("Y amigas no tengo muchas y las que tengo son viejitas y tu señora que pasa hai", {'tags': ['CONJ','NOUN','ADV','VERB','DET','CONJ','DET','PRON','VERB','AUX','ADJ','CONJ','DET','NOUN','PRON','VERB','ADV']}),
    ("Nada estamos ay masoooooo", {'tags': ['PRON','AUX','ADJ','ADJ']}),
    ("U que cagada x que habra sido metiste la pata vos mas que seguro en que andas", {'tags': ['INTJ','PRON','VERB','ADP','SCONJ','AUX','AUX','VERB','DET','NOUN','VERB','ADV','PRON','ADJ','ADP','SCONJ','NOUN']}),
    ("Y siempre algo pinta amiga jaaaaa", {'tags': ['ADV','PRON','VERB','NOUN','NOUN','PUNCT','VERB','NOUN','DET','PROPN','PUNCT']}),
    ("Minas o seguis con esa", {'tags': ['NOUN','CONJ','NOUN','ADP','PRON']}),
    ("Y si eso siempre amiga pero x eso ya no se ase problema", {'tags': ['CONJ','SCONJ','PRON','ADV','ADJ','CONJ','ADP','PRON','ADV','ADV','PRON','VERB','NOUN']}),
    ("Dejate de joder tenes al nene y me salio de cagarte a pedo jiji", {'tags': ['VERB','ADP','NOUN','VERB','ADP','NOUN','CONJ','PRON','NOUN','ADP','VERB','ADP','NOUN','SPACE']}),
    ("Portate bien no seas cabezon , con rason estas tomando con el caceres sigue igual o cambio un poco la locura", {'tags': ['VERB','ADJ','ADV','VERB','ADJ','PUNCT','ADP','NOUN','VERB','VERB','ADP','DET','PROPN','VERB','ADV','CONJ','VERB','DET','ADV','DET','NOUN']}),
    ("El loco sigue igual jaaa ahora un vinito no mas tomamos", {'tags': ['DET','NOUN','VERB','ADJ','SPACE','ADV','DET','NOUN','ADV','ADV','VERB']}),
    ("Jaja y lo que pinte la noche o no pero cuidate", {'tags': ['SPACE','CONJ','DET','PRON','ADV','DET','NOUN','CONJ','ADV','CONJ','VERB']}),
    ("Noooooo ay q descargar temprano amiga asi q un vino y a dormir", {'tags': ['ADV','AUX','SCONJ','VERB','ADV','NOUN','NOUN','SCONJ','DET','NOUN','CONJ','ADP','VERB']}),
    ("A bueno portate bien cabeza y dormi nos estamos viendo cuando tengas tiempo pasa a tomar unos mates", {'tags': ['ADP','ADJ','VERB','ADV','ADJ','CONJ','ADV','PRON','AUX','VERB','SCONJ','VERB','NOUN','VERB','ADP','VERB','DET','NOUN']})
    
]

